# Start from a core stack version
FROM jupyter/scipy-notebook:latest
# Install in the default python3 environment

RUN conda update -n base conda
RUN conda install 'pymc'
RUN conda install 'seaborn'
RUN conda config --add channels conda-forge 
RUN conda install 'ipyparallel'
RUN pip install 'kabuki==0.6.3'
# RUN pip install 'seaborn==0.9.0'
RUN pip install 'tqdm'
RUN pip install 'hddm==0.8.0'

RUN ipcluster nbextension enable

RUN conda clean -a
