# Start from a core stack version
FROM continuumio/miniconda
MAINTAINER hcp4715 <hcp4715@gmail.com>

# add `gcc` so the later the pip could run
RUN apt-get update
RUN apt-get install gcc libc-dev g++ -y
  
COPY hddm.yml .
RUN \
   conda env update -n root -f hddm.yml \
&& conda clean -a
