# Start from a core stack version
FROM jupyter/scipy-notebook:latest
# Install in the default python3 environment

USER root

RUN conda install --quiet --yes \
    'ipyparallel' \
    'pymc' \
    && \
    ipcluster nbextension enable

RUN jupyter notebook --generate-config -y
    
RUN pip install 'kabuki==0.6.3'
RUN pip install 'tqdm'
RUN pip install 'hddm==0.8.0'

USER $NB_UID
WORKDIR $HOME
RUN sed -i  "/# Configuration file for jupyter-notebook./a c.NotebookApp.server_extensions.append('ipyparallel.nbextension')"  /home/jovyan/.jupyter/jupyter_notebook_config.py

RUN conda clean -a
